import { pgTable, text, integer, timestamp, jsonb } from "drizzle-orm/pg-core";

export const siteConfigTable = pgTable("site_config", {
  id: integer("id").primaryKey().default(1),
  title: text("title").notNull(),
  recipientName: text("recipient_name").notNull(),
  senderName: text("sender_name").notNull(),
  startDate: text("start_date").notNull(),
  birthdayDate: text("birthday_date").notNull(),
  accentColor: text("accent_color").notNull(),
  coordinates: text("coordinates").notNull(),
  coordinatesPlace: text("coordinates_place").notNull(),
  unlockOverride: integer("unlock_override").notNull().default(0),
  liveText: text("live_text").notNull().default(""),
  liveUpdatedAt: timestamp("live_updated_at").notNull().defaultNow(),
});

export const daysTable = pgTable("days", {
  slug: text("slug").primaryKey(),
  index: integer("index").notNull(),
  igboTitle: text("igbo_title").notNull().default(""),
  title: text("title").notNull(),
  eyebrow: text("eyebrow").notNull().default(""),
  kind: text("kind").notNull(),
  heroImage: text("hero_image").notNull().default(""),
  body: text("body").notNull().default(""),
  pullQuote: text("pull_quote").notNull().default(""),
  signoff: text("signoff").notNull().default(""),
  songTitle: text("song_title").notNull().default(""),
  songArtist: text("song_artist").notNull().default(""),
  youtubeId: text("youtube_id").notNull().default(""),
  drafts: jsonb("drafts").$type<{ text: string; crossed: boolean }[]>().notNull().default([]),
  reasons: jsonb("reasons").$type<string[]>().notNull().default([]),
  gallery: jsonb("gallery").$type<{ url: string; caption: string; span: "s" | "m" | "l" | "xl" }[]>().notNull().default([]),
  scratchCards: text("scratch_cards").notNull().default("[]"),
  slides: text("slides").notNull().default("[]"),
  signatureSvg: text("signature_svg").notNull().default(""),
  voiceNoteUrl: text("voice_note_url").notNull().default(""),
  previewText: text("preview_text").notNull().default(""),
  replyText: text("reply_text").notNull().default(""),
  replyAt: timestamp("reply_at"),
  openedAt: timestamp("opened_at"),
});
